### ISSUE TITLE
Failed to load model

### ISSUE THREAD

**Issue by yikeda0124** [Xingyu-Lin/VCD#3]
As mentioned in https://github.com/Xingyu-Lin/VCD/issues/2,
I downloaded best_state.json from google drive and place them as shown below. 
(Since the two files had the same name, I created directories named "edge" and "dyn".)
```
VCD
|--VCD
|--chester
|--pretrained
 |--dyn
  |--best_state.json
  |--vsbl_dyn_150.pth
 |--edge
  |--best_state.json
  |--vsbl_edge_best.pth
 ︙
```
Then I ran the following command
`python VCD/main_plan.py --edge_model_path=./pretrained/edge/vsbl_edge_best.pth --partial_dyn_path=./pretrained/dyn/vsbl_dyn_150.pth 
`
And I got
```
Traceback (most recent call last):
  File "VCD/main_plan.py", line 386, in <module>
    main(get_default_args())
  File "VCD/main_plan.py", line 192, in main
    vcd_edge = load_edge_model(args.edge_model_path, env)
  File "VCD/main_plan.py", line 132, in load_edge_model
    vcd_edge = VCConnection(edge_model_args, env=env)
  File "/home/pc/user/VCD/VCD/vc_edge.py", line 33, in __init__
    self.load_model(self.args.load_optim)
  File "/home/pc/user/VCD/VCD/vc_edge.py", line 271, in load_model
    self.model.load_model(self.args.edge_model_path, load_optim=load_optim, optim=self.optim)
  File "/home/pc/user/VCD/VCD/models.py", line 311, in load_model
    ckpt = torch.load(model_path)
  File "/home/pc/anaconda3/envs/softgym/lib/python3.6/site-packages/torch/serialization.py", line 601, in load
    if _is_torchscript_zip(opened_zipfile):
  File "/home/pc/anaconda3/envs/softgym/lib/python3.6/site-packages/torch/serialization.py", line 890, in _is_torchscript_zip
    return 'constants.pkl' in zip_file.get_all_records()
RuntimeError: [enforce fail at inline_container.cc:230] . file in archive is not in a subdirectory archive/: best_state.json
```
How can I fix this error? Thank you:)

**Comment by yufeiwang63** [comment]
I just did a test following exactly our ReadMe, and I can successfully load the model. 
According to google, the error seems to be related to that the stored .pth file is corrupted. Can you double check that you downloaded the pretrained models / best states correctly?

**Comment by yikeda0124** [comment]
I re-unzipped the file and replaced the old model with the new one, and it worked.
It seems that the initial decompression did not work properly.
Thank you very much for your kind instruction.
