### ISSUE TITLE
`main_plan.py` cannot run multiprocessing program, i.e., num_workers >0. When I set num_workers = 0, there are some bugs.

### ISSUE THREAD

**Issue by halid1020** [Xingyu-Lin/VCD#6]
I fixed the bug while using num_workers = 0, but you have data types unmatch problem between the input data and the weights of the model in the encoders.

**Comment by halid1020** [comment]
`highest_return_idx` does not match the dimension of start_poses

**Comment by halid1020** [comment]
Please ensure your code runs properly if you want others to use and compare against it. Thanks :)

**Comment by yufeiwang63** [comment]
Hi,

Thanks for your interest in our project. Can you detail the command you run, and the corresponding error message?

**Comment by halid1020** [comment]
I ran the command
``` 
python VCD/main_plan.py --edge_model_path <provided pretrained model> \
   --partial_dyn_path <provided pretrained model> \
   --num_worker 0
```
on a square fabric simulated environment. 

I got error
```
Traceback (most recent call last):  
  File "VCD/main_plan.py", line 386, in <module>
    main(get_default_args())
  File "VCD/main_plan.py", line 273, in main 
    = planner.get_action(data, cloth_mask=cloth_mask)
  File "/home/ah390/project/VCD/VCD/rs_planner.py", line 154, in get_action
    results = self.pool.map(parallel_generate_actions, params) 
AttributeError: 'RandomShootingUVPickandPlacePlanner' object has no attribute 'pool'
```

**Comment by halid1020** [comment]
When I ran with the default num_worker value as 6
```
python VCD/main_plan.py --edge_model_path <provided pretrained model> \
   --partial_dyn_path <provided pretrained model> 
```

I got error
```
Traceback (most recent call last):
  File "VCD/main_plan.py", line 386, in <module>
    main(get_default_args())
  File "VCD/main_plan.py", line 273, in main
    = planner.get_action(data, cloth_mask=cloth_mask)
  File "/home/ah390/project/VCD/VCD/rs_planner.py", line 184, in get_action
    results = self.pool.map(self.dynamics.rollout, params, chunksize=max(1, pick_try_num // self.num_worker))
  File "/home/ah390/anaconda3/envs/softgym/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/ah390/anaconda3/envs/softgym/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/ah390/anaconda3/envs/softgym/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/home/ah390/anaconda3/envs/softgym/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/ah390/anaconda3/envs/softgym/lib/python3.7/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'torch_geometric.deprecation.DataLoader'>: attribute lookup DataLoader on torch_geometric.deprecation failed
[W CudaIPCTypes.cpp:15] Producer process has been terminated before all shared CUDA tensors released. See Note [Sharing CUDA tensors]
```

**Comment by halid1020** [comment]
I made it work by commenting out the dataloaders.

**Comment by hejia-zhang** [comment]
Hi @halid1020 could you please provide more details about how you solve the problem? We are having the same issues. Thanks!
